### PR TITLE
fix doc/COMPILE.md doc/DOCKER_IMAGES.md by Thomas Young

### PR DESCRIPTION
**Pull request by HexToString**
fix doc/COMPILE.md doc/DOCKER_IMAGES.md by Thomas Young.

### CODE REVIEW

**Comment by HexToString** [comment]
fix doc/COMPILE.md doc/DOCKER_IMAGES.md by Thomas Young.

**Comment by HexToString** [comment]
fix doc/COMPILE.md doc/DOCKER_IMAGES.md by Thomas Young.

**Review by TeslaZhao — DISMISSED** [review]
LGTM

**Review by bjjwwang — APPROVED** [review]
LGTM

**Review by bjjwwang — APPROVED** [review]
LGTM

**Pull request merged**
