### PR TITLE
add gpu_ids description

### PR DESCRIPTION
**Pull request by barrierye**
1. add gpu_ids description in RUN_IN_DOCKER(_CN).md
2. add runtime images description in RUN_IN_DOCKER(_CN).md

### CODE REVIEW

**Comment by barrierye** [comment]
document fix #351

**Comment by barrierye** [comment]
document fix #350

**Review by guru4elephant — DISMISSED** [review]
LGTM

**Review by MRXLT — APPROVED** [review]
LGTM

**Pull request merged**
