### PR TITLE
refine cube benchmark

### PR DESCRIPTION
**Pull request by MRXLT**
修改cube 示例的benchmark脚本，可以一键启动
在general_dist_kv_op.cpp中添加对cube查找部分的耗时统计，这部分耗时在benchmark的脚本中对应op1
prepare_server中添加cube.conf文件路径参数，用户不再需要手动copy
更新cube ci
添加对于cube组件的benchmark脚本

### CODE REVIEW

**Review by guru4elephant — COMMENTED** [review]
Could you add this PR in UT?

**Review by guru4elephant — COMMENTED** [review]
please add this PR to unit test.

**Comment by MRXLT** [comment]
> please add this PR to unit test.
The unit test for cube has been updated

**Comment by MRXLT** [comment]
> please add this PR to unit test.

The unit test for cube has been updated

**Review by bjjwwang — APPROVED** [review]
LGTM

**Pull request merged**
